/* ============================================================
   JOURNEY — where the open film is, across the five stages
   ------------------------------------------------------------
   One derivation, read by the hub's journey strip, the dashboard and
   the project cards. It STORES NOTHING and must stay that way: every
   answer is computed at render time from the models that already own
   the facts, for the reason readiness.js gives — a cached "current
   stage" is a second copy of an answer that is wrong the first time
   either copy is edited, and a dashboard that writes on load trips
   verify's idle-write check.

   TWO MEASURES PER STAGE, because the studio has two ways of doing
   the same work and a writer may use either, both, or neither:

     guide   the blueprint's steps for that stage — feature.html or
             short.html — counted with the blueprint's own rule for
             "filled" (blueprint-fields.js: a non-empty string or a
             ticked item). A step is COMPLETE when every field it
             declares is filled, which is the rule the blueprint's
             own step badges use ("✓ COMPLETE" at 100%).
     tools   the stage's real modules, asked a few yes/no questions
             each, from the models:
               story       fms_story_v1: logline, outline, synopsis,
                           tagged passages            (story.js)
               screenplay  the script and the scene list
                           (script.js, scenes.js)
               preprod     every readiness() check   (readiness.js)
               production  scenes marked shot        (shootday.js)
               post        scenes in the cut and the deliverables
                           list                      (editlog.js,
                           deliverables.js)

   WHICH STEP BELONGS TO WHICH STAGE. src/data/steps.stages.json is
   the sidecar that owns this (the step files are regenerated by
   `npm run extract`, so the fact cannot live in them). When it is
   present it wins; the table below is the fallback that matches the
   approved plan, so this file works in a checkout without it:

     feature  01–10 story · 11–13 screenplay · 14–24 preprod ·
              25–28 production · 29–32 post
     short    1–5 story · 6–8 screenplay · 9 preprod · 10–11 post
              (step 9 "Production Reality" is the short's planning
              step — a schedule, a budget, a crew — so it sits under
              Pre-Production and the short has no production step)

   "CURRENT" — the earliest stage that is not substantially done.
   The heuristic, in full:

     guideOK  the stage has no guide steps, or ≥ 80% of its guide
              FIELDS are filled
     toolsOK  ≥ 75% of the stage's tool checks pass (a stage whose
              tools have nothing to measure yet — production with no
              scenes — is NOT ok: zero of zero is not done)
     done     toolsOK && (guideOK || work has started in a later
              stage's tools)

   The last clause is what keeps the guide optional. The tools are the
   work; the blueprint is a companion. Somebody who has a script, a
   schedule and shots logged but never opened the blueprint is not
   "in Story", and somebody who has filled every step of Part I but
   has no logline in the Story module has not finished the story
   either. When every stage is done, current is the last one and
   `complete` is true.

   "NEXT" — one action for the current stage. A failing tool check
   first (the work), then the first incomplete guide step of that
   stage (the companion). Hrefs point into the module or the
   blueprint step that owns the gap.
   ============================================================ */
import './store.js';   // must evaluate before anything reads localStorage
import nav from '../data/navigation.json';
import featureData from '../data/steps.feature.json';
import prodData from '../data/steps.production.json';
import shortData from '../data/steps.short.json';
import { harvestKeys, isFilled } from './blueprint-fields.js';
import Scenes from './scenes.js';
import { loadScript, pageCount, formatPages, hasTitlePage } from './script.js';
import * as StoryM from './story.js';
import Locations from './locations.js';
import * as StoreM from './store.js';
const { loadStory } = StoryM;
import { readiness } from './readiness.js';
import { overall as shootOverall } from './shootday.js';
import { coverage } from './editlog.js';
import { listItems, progress as deliverablesProgress } from './deliverables.js';

/* ---- the stages, from navigation.json ---------------------- */
const PART = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'];

export const STAGES = nav.phases.map((p, i) => ({
  id: p.id,
  label: p.label,
  hue: p.id,               // the .sh-ph-<id> class family in tokens.css
  part: PART[i] || String(i + 1)
}));
const STAGE_BY_ID = new Map(STAGES.map((s) => [s.id, s]));
export const stageById = (id) => STAGE_BY_ID.get(id) || null;

/** The class that sets --hue for a stage. tokens.css defines exactly
    .sh-ph-story/-screenplay/-preprod/-production/-post; anything else
    fails silently, which is why the name is built in one place. */
export const stageHueClass = (id) => 'sh-ph-' + id;

/* ---- which step is in which stage ------------------------- */
const FALLBACK = {
  feature: (n) => (n <= 10 ? 'story' : n <= 13 ? 'screenplay' : n <= 24 ? 'preprod'
                   : n <= 28 ? 'production' : 'post'),
  short: (n) => (n <= 5 ? 'story' : n <= 8 ? 'screenplay' : n === 9 ? 'preprod' : 'post')
};

/* The sidecar, when this checkout has it. A glob rather than an
   import so a missing file is an empty object instead of a build
   error. Called bare inside the try, NOT behind a typeof test: Vite
   rewrites the call expression at build time but leaves
   `typeof import.meta.glob` alone, and in the browser that is
   "undefined" — the guard would have discarded the sidecar on every
   page. Under Node (no Vite) the bare call throws and lands in the
   catch, which is the fallback. */
const SIDECAR = (() => {
  try {
    const mods = import.meta.glob('../data/steps.stages.json', { eager: true });
    const mod = Object.values(mods)[0];
    return (mod && (mod.default || mod)) || null;
  } catch (e) { return null; }
})();

/* Tolerant about the sidecar's shape, because it is being written in
   parallel: a value may be the stage id itself or an object carrying
   `stage`; keys may be `ns:step-id` (the steps.priority.json
   convention), or nested under the namespace by id or by number. */
function sidecarStage(ns, stepId) {
  if (!SIDECAR || typeof SIDECAR !== 'object') return null;
  const num = String(stepId).replace(/^step-/, '');
  const pick = (v) => (typeof v === 'string' ? v : v && typeof v === 'object' ? v.stage : null);
  const pools = [SIDECAR, SIDECAR.steps, SIDECAR[ns], SIDECAR.steps && SIDECAR.steps[ns]];
  for (const pool of pools) {
    if (!pool || typeof pool !== 'object') continue;
    if (Array.isArray(pool)) {
      const row = pool.find((r) => r && (r.step === ns + ':' + stepId ||
        ((!r.ns || r.ns === ns) && (r.id === stepId || r.step === stepId))));
      const st = row && pick(row);
      if (st && STAGE_BY_ID.has(st)) return st;
      continue;
    }
    for (const k of [ns + ':' + stepId, stepId, num]) {
      const st = pick(pool[k]);
      if (st && STAGE_BY_ID.has(st)) return st;
    }
  }
  return null;
}

/** The stage a blueprint step belongs to. `ns` is 'feature' or 'short'. */
export function stageOfStep(ns, stepId) {
  const fromFile = sidecarStage(ns, stepId);
  if (fromFile) return fromFile;
  const n = parseInt(String(stepId).replace(/^step-/, ''), 10);
  const fn = FALLBACK[ns === 'short' ? 'short' : 'feature'];
  return Number.isFinite(n) ? fn(n) : 'story';
}

/* ---- the guide: blueprint steps as field lists ------------- */
export const FEATURE_KEY = 'fms_filmmaker_combined_v1';
export const SHORT_KEY = 'fms_shortfilm_blueprint_v1';

export const BLUEPRINT = {
  feature: { id: 'feature', label: 'Feature Blueprint', href: 'feature.html', storeKey: FEATURE_KEY },
  short:   { id: 'short',   label: 'Short Blueprint',   href: 'short.html',   storeKey: SHORT_KEY }
};

/** Which blueprint a project format is guided by. */
export const blueprintFor = (format) => (format === 'short' ? 'short' : 'feature');

const plainTitle = (s) =>
  String(s.titlePlain || s.title || '').replace(/<[^>]*>/g, '').replace(/\.$/, '').trim();

const hasBlock = (step, type) => (step.blocks || []).some((b) => b.type === type);

/* The short film's five beats live in their own array and are rendered
   by the `beatviz` block inside step 4, so they are counted there —
   the attribution the dashboard has always made. */
function stepFields(step, ns) {
  const keys = harvestKeys(step, new Set());
  if (ns === 'short' && hasBlock(step, 'beatviz')) harvestKeys(shortData.beats, keys);
  return keys;
}

const STEP_CACHE = {};
/** Every step of a blueprint, in order, with its field set and stage.
    Built once: the step data is a build-time import. */
export function guideSteps(ns) {
  const key = ns === 'short' ? 'short' : 'feature';
  if (!STEP_CACHE[key]) {
    const raw = key === 'short'
      ? shortData.steps
      : [...featureData.vol1, ...featureData.vol2, ...prodData.production, ...prodData.post];
    STEP_CACHE[key] = raw.map((s) => ({
      id: s.id,
      num: s.num,
      title: plainTitle(s),
      deck: String(s.deck || '').replace(/<[^>]*>/g, ''),
      stage: stageOfStep(key, s.id),
      keys: stepFields(s, key)
    }));
  }
  return STEP_CACHE[key];
}

/**
 * Guide progress for one blueprint blob, grouped by stage. Pure: pass
 * the blob, get the counts — which is what lets the hub's project
 * cards ask about projects that are not open.
 *
 * @returns {{ns, stages: Array<{id,label,hue,part,steps,done,total,
 *            fields:{done,total}, pct}>, fields:{done,total}, pct}}
 *          `done`/`total` count COMPLETE steps; `pct` is by field.
 */
export function guideProgress(ns, data) {
  const blob = data && typeof data === 'object' ? data : {};
  const steps = guideSteps(ns).map((s) => {
    let done = 0;
    for (const k of s.keys) if (isFilled(blob[k])) done++;
    return { ...s, fieldsDone: done, fieldsTotal: s.keys.size,
             complete: s.keys.size > 0 && done === s.keys.size };
  });
  let fd = 0, ft = 0;
  const stages = STAGES.map((st) => {
    const mine = steps.filter((s) => s.stage === st.id);
    const done = mine.filter((s) => s.complete).length;
    const fDone = mine.reduce((n, s) => n + s.fieldsDone, 0);
    const fTotal = mine.reduce((n, s) => n + s.fieldsTotal, 0);
    fd += fDone; ft += fTotal;
    return {
      ...st, steps: mine, done, total: mine.length,
      fields: { done: fDone, total: fTotal },
      pct: fTotal ? Math.round((fDone / fTotal) * 100) : 0
    };
  });
  return { ns, stages, fields: { done: fd, total: ft }, pct: ft ? Math.round((fd / ft) * 100) : 0 };
}

/* ---- reading a blob through the proxy (the open project) ---- */
function readBlob(key) {
  let raw = null;
  try { raw = localStorage.getItem(key); } catch (e) { /* private mode */ }
  if (!raw) return {};
  try {
    const p = JSON.parse(raw);
    return p && typeof p === 'object' ? p : {};
  } catch (e) { return {}; }
}

/* ---- the tools, per stage ---------------------------------- */
const check = (label, ok, href, todo) => ({ label, ok: !!ok, href, todo: todo || label });
const plural = (n, one, many) => n + ' ' + (n === 1 ? one : (many || one + 's'));

function storyTools() {
  const s = loadStory();
  const outline = Array.isArray(s.outline) ? s.outline.filter((o) => o && String(o.text || '').trim()) : [];
  const checks = [
    check('Logline', String(s.logline || '').trim(), 'story.html', 'Write the logline'),
    check('Step outline', outline.length > 0, 'story.html', 'Build the step outline'),
    check('Synopsis', String(s.source || '').trim(), 'story.html', 'Write or import the synopsis'),
    check('Beats tagged', (s.marks || []).length > 0, 'story.html', 'Tag the beats in your synopsis')
  ];
  const bits = [];
  if (outline.length) bits.push(plural(outline.length, 'outline step'));
  if ((s.marks || []).length) bits.push(plural(s.marks.length, 'tagged passage'));
  return { checks, note: bits.join(' · ') || (checks[2].ok ? 'Synopsis written' : 'Nothing written yet') };
}

function screenplayTools(ctx) {
  const script = loadScript();
  const els = script.elements || [];
  const headings = els.filter((e) => e.type === 'scene').length;
  const checks = [
    check('Screenplay started', els.length > 0, 'write.html#screenplay', 'Start the screenplay'),
    check('Scene headings', headings > 0, 'write.html#screenplay', 'Add scene headings to the script'),
    check('Title page', hasTitlePage(script.titlePage), 'write.html#screenplay', 'Fill in the title page'),
    check('Scene list', ctx.scenes.length > 0, 'breakdown.html#scenes', 'Build the scene list')
  ];
  const bits = [];
  if (els.length) bits.push(formatPages(pageCount(els)) + ' pp');
  if (ctx.scenes.length) bits.push(plural(ctx.scenes.length, 'scene'));
  return { checks, note: bits.join(' · ') || 'No script yet' };
}

function preprodTools() {
  const r = readiness();
  if (!r.hasFilm) {
    return {
      checks: [check('Scenes to plan from', false, 'breakdown.html#scenes', 'Add scenes to plan from')],
      note: 'No scenes yet'
    };
  }
  const checks = r.checks.map((c) => check(c.label, c.passed, c.where || 'dashboard.html#readiness',
    c.label + (c.count ? ' (' + c.count + ')' : '')));
  const note = r.blockers
    ? plural(r.blockers, 'blocker') + (r.gaps ? ' · ' + plural(r.gaps, 'gap') : '')
    : r.gaps ? plural(r.gaps, 'gap') : 'Every check passes';
  return { checks, note };
}

/* Production and post are COUNTS rather than checklists: one row per
   scene is the honest unit, and twelve checks of "scene 4 is shot"
   would say the same thing less readably. */
function productionTools(ctx) {
  const o = shootOverall(ctx.scenes);
  return {
    done: o.done, total: o.scenes,
    next: o.scenes ? { label: 'Mark today’s scenes on the shoot day', href: 'shoot.html' }
                   : { label: 'Add scenes to shoot', href: 'breakdown.html#scenes' },
    note: o.scenes ? o.done + ' of ' + plural(o.scenes, 'scene') + ' shot' : 'No scenes yet'
  };
}

function postTools(ctx) {
  const cov = coverage(ctx.scenes);
  const dl = deliverablesProgress(listItems(ctx.format));
  const need = cov.counts.need;
  const inCut = Math.min(cov.counts.inCut, need);
  const cutOpen = need > 0 && inCut < need;
  return {
    done: inCut + dl.done, total: need + dl.total,
    next: cutOpen ? { label: 'Log the cut', href: 'edit.html#log' }
                  : { label: 'Work through the deliverables', href: 'deliverables.html#checklist' },
    note: (need ? inCut + ' of ' + need + ' scenes in the cut · ' : '')
        + dl.done + ' of ' + dl.total + ' deliverables'
  };
}

function fromChecks({ checks, note }) {
  const failing = checks.find((c) => !c.ok);
  return {
    done: checks.filter((c) => c.ok).length,
    total: checks.length,
    note,
    checks,
    next: failing ? { label: failing.todo, href: failing.href } : null
  };
}

/* One broken model must not take the strip off the page — a stage
   whose tools could not be read reports nothing measured. */
function safely(fn, ctx) {
  try { return fn(ctx); } catch (e) {
    console.warn('[journey]', e);
    return { done: 0, total: 0, note: 'Could not be read', next: null };
  }
}

const TOOLS = {
  story:      (ctx) => fromChecks(storyTools(ctx)),
  screenplay: (ctx) => fromChecks(screenplayTools(ctx)),
  preprod:    (ctx) => fromChecks(preprodTools(ctx)),
  production: productionTools,
  post:       postTools
};

/* ---- the heuristic ------------------------------------------ */
const GUIDE_OK = 0.8;
const TOOLS_OK = 0.75;

const guideOK = (g) => g.fields.total === 0 || g.fields.done / g.fields.total >= GUIDE_OK;
const toolsOK = (t) => t.total > 0 && t.done / t.total >= TOOLS_OK;

function pickCurrent(stages) {
  for (let i = 0; i < stages.length; i++) {
    const s = stages[i];
    const laterWork = stages.slice(i + 1).some((x) => x.tools.done > 0);
    const done = toolsOK(s.tools) && (guideOK(s.guide) || laterWork);
    if (!done) return { index: i, complete: false };
  }
  return { index: stages.length - 1, complete: true };
}

/* The blueprint is a companion now, not a destination: nothing here
   builds a feature.html#step-xx href as a "next" any more. When a
   stage has no failing tool check the answer is the stage's own page. */
function stageFallback(st) {
  return { label: 'Continue in ' + st.label, href: stageHref(st.id) };
}

/**
 * Where the open project stands.
 *
 * @param {object} [project]  { id, title, format } — defaults to the
 *                            open project. Its models are read through
 *                            the storage proxy, so it MUST be the open
 *                            one; for any other project use
 *                            guideJourney().
 * @returns {null | {
 *   stages: Array<{id, label, hue, part,
 *                  guide: {done, total, pct, fields:{done,total}},
 *                  tools: {done, total, pct, note},
 *                  ok: {guide, tools}}>,
 *   current: string, currentLabel: string, complete: boolean,
 *   next: {label, href, stage}, blueprint: {id,label,href}
 * }}  null when no project is open.
 */
export function journey(project) {
  const p = project || null;
  if (!p) return null;
  const ns = blueprintFor(p.format);
  const bp = BLUEPRINT[ns];
  const guide = guideProgress(ns, readBlob(bp.storeKey));
  let scenes = [];
  try { scenes = Scenes.listScenes(); } catch (e) { scenes = []; }
  const ctx = { scenes, format: p.format };

  const stages = STAGES.map((st, i) => {
    const g = guide.stages[i];
    const t = safely(TOOLS[st.id] || (() => ({ done: 0, total: 0, note: '', next: null })), ctx);
    return {
      id: st.id, label: st.label, hue: st.hue, part: st.part,
      guide: { done: g.done, total: g.total, pct: g.pct, fields: g.fields, steps: g.steps },
      tools: { done: t.done, total: t.total, note: t.note || '', next: t.next || null,
               pct: t.total ? Math.round((t.done / t.total) * 100) : 0 }
    };
  });
  stages.forEach((s) => { s.ok = { guide: guideOK(s.guide), tools: toolsOK(s.tools) }; });

  const { index, complete } = pickCurrent(stages);
  const cur = stages[index];
  let next = null;
  if (!complete) {
    next = cur.tools.next || stageFallback(cur);
  }
  if (!next) next = { label: 'Review the deliverables', href: 'deliverables.html#checklist' };

  /* steps arrays are for the dashboard's detail; the strip needs only
     the counts, so they are left on `guide` but never rendered there. */
  return {
    stages,
    current: cur.id,
    currentLabel: cur.label,
    complete,
    next: { ...next, stage: cur.id },
    blueprint: { id: bp.id, label: bp.label, href: bp.href }
  };
}

/**
 * The guide-only answer, for a project that is NOT open (the hub's
 * project cards). Its tools live behind the proxy under another id,
 * and reading them would mean a second, raw-key copy of every model's
 * loader — so the cards say where the BLUEPRINT is, and only the open
 * project's card says where the film is.
 *
 * @param {string} format
 * @param {object} data   the project's blueprint blob
 * @returns {{current, currentLabel, started: boolean, pct}}
 */
export function guideJourney(format, data) {
  const g = guideProgress(blueprintFor(format), data);
  const started = g.fields.done > 0;
  let cur = g.stages.find((s) => s.fields.total && s.fields.done / s.fields.total < GUIDE_OK);
  if (!cur) cur = g.stages[g.stages.length - 1];
  if (!started) cur = g.stages[0];
  return { current: cur.id, currentLabel: cur.label, started, pct: g.pct };
}

/**
 * The step to pick up at: the first, in blueprint order, whose fields
 * are not all filled. The dashboard's "Continue" and the hub's resume
 * card both read this, so the two "pick up where you left off"s name
 * one step (the hub's used to be the HIGHEST-numbered step with any
 * data, which on the sample sent you to step 24 while the dashboard
 * said 08). Null for a blob with nothing in it, or every step done.
 */
export function nextGuideStep(ns, data) {
  const g = guideProgress(ns, data);
  if (!g.fields.done) return null;
  for (const st of g.stages) for (const s of st.steps) if (s.fieldsTotal && !s.complete) return s;
  return null;
}

/* ============================================================
   THE STAGE CARDS — state per stage, no gating
   ------------------------------------------------------------
   The dashboard's answer, and it is deliberately NOT journey()'s
   "current stage" heuristic. Nothing is mandatory: somebody with a
   script in hand starts in Pre-production and Story stays "Not
   started" without that being a fault. So each stage reports ONLY on
   its own models (status none | doing | done), and the suggestion is
   a separate, derived nudge.

   Stores nothing; reads the models through the proxy, so it is
   correct for the OPEN project only.
   ============================================================ */
export const STATUS = {
  none:  { id: 'none',  label: 'Not started' },
  doing: { id: 'doing', label: 'In progress' },
  done:  { id: 'done',  label: 'Done' }
};

/** A stage's main page, from navigation.json (the stage's first module). */
export function stageHref(id) {
  const ph = nav.phases.find((p) => p.id === id);
  const m = ph && ph.modules && ph.modules[0];
  return (m && m.href) || 'dashboard.html';
}

const plur = (n, one, many) => n + ' ' + (n === 1 ? one : (many || one + 's'));
const status = (done, any) => (done ? STATUS.done : any ? STATUS.doing : STATUS.none);
const tsOf = (v) => {
  const n = typeof v === 'number' ? v : Date.parse(v || '');
  return Number.isFinite(n) && n > 0 ? n : 0;
};

function storyState() {
  const s = loadStory();
  const hasText = !!(String(s.logline || '').trim() || String(s.idea || '').trim()
    || String(s.source || '').trim() || (s.outline || []).some((o) => String(o.text || '').trim())
    || (s.marks || []).length);
  let done = 0, total = 0, labelled = '';
  /* pathProgress arrives from the Story lane; PATH may grow a step. Use
     whatever length it returns, and fall back to four plain checks. */
  if (typeof StoryM.pathProgress === 'function') {
    try {
      const path = StoryM.pathProgress(s, { scenes: Scenes.listScenes() });
      if (Array.isArray(path) && path.length) {
        total = path.length; done = path.filter((p) => p && p.done).length;
        labelled = 'story path steps';
      }
    } catch (e) { /* fall through to the checks */ }
  }
  if (!total) {
    const ok = [String(s.logline || '').trim(), (s.outline || []).some((o) => String(o.text || '').trim()),
      String(s.source || '').trim(), (s.marks || []).length > 0];
    total = ok.length; done = ok.filter(Boolean).length; labelled = 'story steps';
  }
  const facts = [done + ' of ' + total + ' ' + labelled + ' done'];
  const words = String(s.source || '').trim().split(/\s+/).filter(Boolean).length;
  if (words) facts.push(plur(words, 'word') + ' of synopsis');
  return { status: status(total > 0 && done >= total, done > 0 || hasText), facts, at: tsOf(s.updatedAt) };
}

function screenplayState() {
  const sc = loadScript();
  const els = sc.elements || [];
  const heads = els.filter((e) => e.type === 'scene').length;
  const any = els.some((e) => String(e.text || '').trim());
  const facts = any ? [formatPages(pageCount(els)) + ' pages', plur(heads, 'scene heading')] : ['No script yet'];
  const done = any && heads > 0 && hasTitlePage(sc.titlePage);
  return { status: status(done, any), facts, at: 0 };
}

function preprodState(scenes) {
  const n = scenes.length;
  if (!n) return { status: STATUS.none, facts: ['No scenes yet'], at: 0 };
  const tagged = scenes.filter((s) => Object.values(s.elements || {})
    .some((v) => Array.isArray(v) && v.length)).length;
  const locs = new Set(scenes.map((s) => String(s.location || '').trim().toLowerCase()).filter(Boolean)).size;
  let days = 0;
  try { days = Locations.calendarDays(scenes).length; } catch (e) { /* none */ }
  let blockers = 0, gaps = 0, hasFilm = false;
  try { const r = readiness(); hasFilm = r.hasFilm; blockers = r.blockers; gaps = r.gaps; } catch (e) { /* none */ }
  const facts = [plur(n, 'scene') + ' · ' + tagged + ' broken down',
    plur(locs, 'location') + ' · ' + plur(days, 'shoot day')];
  return { status: status(hasFilm && !blockers && !gaps && tagged === n && days > 0, true), facts, at: 0 };
}

function productionState(scenes) {
  const marked = scenes.filter((s) => s.shotState);
  const shot = marked.filter((s) => s.shotState === 'shot').length;
  const part = marked.filter((s) => s.shotState === 'part').length;
  const dropped = marked.filter((s) => s.shotState === 'dropped').length;
  const at = marked.reduce((m, s) => Math.max(m, tsOf(s.shotAt)), 0);
  if (!scenes.length) return { status: STATUS.none, facts: ['No scenes to shoot yet'], at };
  const facts = [shot + ' of ' + plur(scenes.length, 'scene') + ' shot'];
  if (part) facts.push(part + ' part-shot');
  if (dropped) facts.push(dropped + ' dropped');
  return { status: status(shot + dropped === scenes.length, marked.length > 0), facts, at };
}

function postState(scenes, format) {
  const cov = coverage(scenes);
  const dl = deliverablesProgress(listItems(format));
  const need = cov.counts.need;
  const inCut = Math.min(cov.counts.inCut, need);
  const any = cov.counts.inCut > 0 || cov.counts.out > 0 || dl.done > 0 || dl.doing > 0;
  const facts = [need ? inCut + ' of ' + plur(need, 'scene') + ' in the cut' : 'No cut logged yet',
    dl.done + ' of ' + dl.total + ' deliverables'];
  return { status: status(need > 0 && inCut >= need && dl.complete, any), facts, at: 0 };
}

/** The favourite film as { slug, title } or null. Tolerant: the setter
    lives in store.js on another lane's branch. `titleOf(slug)` is the
    caller's lookup — studies.js carries four films' data, so this module
    (in the first paint of the hub and the dashboard) must not import it. */
export function favouriteOf(project, titleOf) {
  try {
    if (typeof StoreM.projectFav !== 'function') return null;
    const v = StoreM.projectFav(project && project.id);
    const slug = typeof v === 'string' ? v : v && v.slug;
    if (!slug) return null;
    return { slug, title: (typeof titleOf === 'function' && titleOf(slug)) || (v && v.title) || slug };
  } catch (e) { return null; }
}

const START = {
  screenplay: { label: 'Already have a script? Import it', href: 'write.html#wr-import' },
  preprod:    { label: 'Have a script? Upload it and we’ll break it down', href: 'breakdown.html' }
};

/**
 * Every stage's state for the OPEN project. No stage depends on another.
 * @returns {Array<{id,label,hue,part,href,status,facts,at,start}>}
 */
export function stageStates(project) {
  let scenes = [];
  try { scenes = Scenes.listScenes(); } catch (e) { scenes = []; }
  const fmt = project && project.format;
  const readers = {
    story: () => storyState(), screenplay: () => screenplayState(),
    preprod: () => preprodState(scenes), production: () => productionState(scenes),
    post: () => postState(scenes, fmt)
  };
  return STAGES.map((st) => {
    let r;
    try { r = readers[st.id](); } catch (e) {
      console.warn('[journey]', e);
      r = { status: STATUS.none, facts: ['Could not be read'], at: 0 };
    }
    return { id: st.id, label: st.label, hue: st.hue, part: st.part, href: stageHref(st.id),
      status: r.status, facts: r.facts, at: r.at || 0, start: START[st.id] || null };
  });
}

/**
 * The suggestion, never a gate. Nothing touched: the first stage.
 * Otherwise the unfinished stage with work — the most recently worked
 * where a timestamp exists, else the furthest along in film order. If
 * every started stage is finished: the earliest stage not started.
 * Null when all are done.
 * @returns {null | {id, why}}
 */
export function suggestNext(states) {
  const list = states || [];
  if (!list.length) return null;
  const started = list.filter((s) => s.status.id !== 'none');
  if (!started.length) return { id: list[0].id, why: 'start' };
  const open = started.filter((s) => s.status.id === 'doing');
  if (open.length) {
    const pick = open.reduce((best, s) => (!best || s.at > best.at
      || (s.at === best.at && list.indexOf(s) > list.indexOf(best)) ? s : best), null);
    return { id: pick.id, why: 'continue' };
  }
  const first = list.find((s) => s.status.id === 'none');
  return first ? { id: first.id, why: 'next' } : null;
}

/** "Resume where you left off": the stage with the newest timestamp the
    models carry (story.updatedAt, scene shotAt), or null. */
export function lastWorked(states) {
  return (states || []).filter((s) => s.at > 0).sort((a, b) => b.at - a.at)[0] || null;
}

export default {
  STAGES, stageById, stageHueClass, stageOfStep, guideSteps, guideProgress, nextGuideStep,
  journey, guideJourney, blueprintFor, BLUEPRINT,
  stageStates, suggestNext, lastWorked, stageHref, favouriteOf
};
