/* ============================================================
   STEP STAGES — which of the five stages a blueprint step is in,
   where in the app it is done, and what the app already knows
   ------------------------------------------------------------
   docs/BLUEPRINT-REALIGN-PLAN.md, revision 3, section 3. Three
   things on every step of both blueprints:

     1. a STAGE CHIP — "PART II · SCREENPLAY", in that stage's hue;
     2. a "DO THIS IN…" row — buttons to the modules that do the
        step's work for real;
     3. on a few steps, a LIVE READOUT — "36 scenes · 105 pages".

   ALL OF IT IS DERIVED. The mapping is src/data/steps.stages.json
   (a sidecar, because the step files are regenerated by
   `npm run extract`). Labels, hrefs and hues come from
   navigation.json through src/lib/navmodel.js at render time, so a
   module renamed there is renamed here with no edit. The readouts
   READ the scene, script, schedule and contact models and store
   nothing — not a cache, not a "last seen" count. The idle-write
   assertion in verify is watching this page.

   THE HUE CLASS IS `.sh-ph-<phase.hue>`. A stage's hue goes through
   the phase family in tokens.css; a name in neither family matches
   no rule, --hue stays undefined and the chip renders grey without
   an error (CLAUDE.md, the --hue trap). It is read from the phase
   object, never typed.
   ============================================================ */

import { h } from '../lib/dom.js';
import nav from '../data/navigation.json';
import { allModules } from '../lib/navmodel.js';
import STAGES from '../data/steps.stages.json';
import { listScenes, totalEighths, formatEighths } from '../lib/scenes.js';
import { calendarDays, unplacedScenes } from '../lib/locations.js';
import { listContacts } from '../lib/contacts.js';
import { loadScript, pageCount, formatPages } from '../lib/script.js';
import { days as shootDays, pickDay } from '../lib/shootday.js';

const PHASES = new Map(nav.phases.map((p) => [p.id, p]));
const STEPS = STAGES.steps || {};

/* ---- small derivations ------------------------------------ */

const ROMAN = ['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'];
export const roman = (n) => ROMAN[n] || String(n);

const ONES = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight',
  'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen',
  'seventeen', 'eighteen', 'nineteen'];
const TENS = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety'];

/** 32 → "thirty-two". Counts on a cover are derived, so their words are too. */
export function numberWord(n) {
  n = Math.max(0, Math.floor(Number(n) || 0));
  if (n < 20) return ONES[n];
  if (n < 100) return TENS[Math.floor(n / 10)] + (n % 10 ? '-' + ONES[n % 10] : '');
  return String(n);
}
export const capitalise = (s) => String(s).charAt(0).toUpperCase() + String(s).slice(1);

const list = (v) => (Array.isArray(v) ? v : v == null ? [] : [v]);
const plural = (n, one, many) => n + ' ' + (n === 1 ? one : (many || one + 's'));

/* An unresolved id is reported ONCE, loudly for a developer and
   harmlessly for a user — the same rule the spine follows. */
const warned = new Set();
function warnOnce(what) {
  if (warned.has(what)) return;
  warned.add(what);
  console.warn('[step-stages] steps.stages.json names something navigation.json does not:', what);
}

/* ---- lookups ---------------------------------------------- */

/** The sidecar entry for `<ns>:<id>`, with its stages resolved, or null. */
export function stageInfo(ns, id) {
  const raw = ns && id ? STEPS[ns + ':' + id] : null;
  if (!raw) return null;
  const stages = list(raw.stage).map((sid) => {
    const p = PHASES.get(sid);
    if (!p) warnOnce('stage ' + sid);
    return p;
  }).filter(Boolean);
  return {
    stages,
    parts: list(raw.part).filter((n) => Number.isFinite(n)),
    lock: !!raw.lock,
    tools: list(raw.tools),
    readout: raw.readout || ''
  };
}

/** The feature page's parts, in order, each with its phase object. */
export function partsOf(ns) {
  return list((STAGES.parts || {})[ns]).map((p) => ({ ...p, phase: PHASES.get(p.stage) }))
    .filter((p) => p.phase);
}

/** Every sidecar entry in a part, as `{ ns, id }`, in file order. */
export function idsInPart(part) {
  return Object.entries(STEPS)
    .filter(([, v]) => list(v.part).includes(part))
    .map(([k]) => ({ ns: k.slice(0, k.indexOf(':')), id: k.slice(k.indexOf(':') + 1) }));
}

const stageName = (stages) => stages.map((p) => p.label.toUpperCase()).join(' & ');

/** "PART II · SCREENPLAY", "PARTS III–IV · PRE-PRODUCTION & PRODUCTION",
 *  "FINAL LOCK · SCREENPLAY". */
export function partLabel(info) {
  if (!info) return '';
  const name = stageName(info.stages);
  if (info.lock) return 'FINAL LOCK' + (name ? ' · ' + name : '');
  const ps = info.parts;
  const head = !ps.length ? ''
    : ps.length === 1 ? 'PART ' + roman(ps[0])
      : 'PARTS ' + roman(ps[0]) + '–' + roman(ps[ps.length - 1]);
  return [head, name].filter(Boolean).join(' · ');
}

/** The rail and the jump menu group a part by its own label. */
export function partHeading(part) {
  const p = partsOf('feature').find((x) => x.part === part);
  return p ? 'PART ' + roman(part) + ' · ' + p.phase.label.toUpperCase() : 'PART ' + roman(part);
}

/** Resolve a `tools` entry to `{ label, href }`, or null. */
export function resolveTool(entry) {
  const mods = allModules();
  if (typeof entry === 'string') {
    const m = mods.find((x) => x.id === entry);
    if (!m || !m.href) { warnOnce('module ' + entry); return null; }
    return { label: m.label, href: m.href };
  }
  if (!entry || typeof entry !== 'object' || !entry.href) return null;
  let lead = '';
  if (entry.module) {
    const m = mods.find((x) => x.id === entry.module);
    if (!m) { warnOnce('module ' + entry.module); return null; }
    lead = m.label;
  } else if (entry.place) {
    const g = nav.global.find((x) => x.href === entry.place);
    if (!g) { warnOnce('place ' + entry.place); return null; }
    lead = g.label;
  }
  return { label: [lead, entry.sub].filter(Boolean).join(' › '), href: entry.href };
}

/* ---- the row ---------------------------------------------- */

/** The chip(s) for a step, each in its own stage's hue. */
export function stageChips(info) {
  if (!info || !info.stages.length) return null;
  const wrap = h('span.st-stage-chips');
  wrap.append(h('span.st-stage-chip.sh-ph-' + info.stages[0].hue, { text: partLabel(info) }));
  /* A step spanning two stages shows the second hue as a swatch
     beside the chip, so the colour coding says both and the words
     are not printed twice. */
  for (const p of info.stages.slice(1)) {
    wrap.append(h('span.st-stage-swatch.sh-ph-' + p.hue, { 'aria-hidden': 'true' }));
  }
  return wrap;
}

/**
 * The stage chip, the "Do this in…" buttons and an empty readout
 * slot, as one row under a step's header. Null when the sidecar does
 * not know the step — a step it forgot is better unmarked than
 * marked wrong.
 */
export function stageRow(ns, id) {
  const info = stageInfo(ns, id);
  if (!info) return null;
  const row = h('div.st-stage-row', { 'data-st-stage': info.stages.map((p) => p.id).join(' ') });
  const chips = stageChips(info);
  if (chips) row.append(chips);

  const tools = info.tools.map(resolveTool).filter(Boolean);
  if (tools.length) {
    row.append(h('span.st-tools', {}, [
      h('span.st-tools-label', { text: 'DO THIS IN' }),
      ...tools.map((t) => h('a.btn.st-tool', { href: t.href, text: t.label + ' →' }))
    ]));
  }
  if (info.readout) {
    row.append(h('span.st-readout', { 'data-st-readout': info.readout, role: 'status' }));
  }
  return row;
}

/* ---- live readouts -----------------------------------------
   Each returns `{ text, empty, cta }`. `cta` is a tools entry,
   resolved the same way the row's buttons are. Cheap on purpose:
   one listScenes() per readout, no layout, no storage writes. */

const EMPTY_FILM = { text: 'Nothing in the Breakdown yet', empty: true, cta: 'breakdowns' };

const READOUTS = {
  scenes() {
    const scenes = listScenes();
    if (!scenes.length) return EMPTY_FILM;
    const noLoc = unplacedScenes(scenes).length;
    const pages = formatEighths(totalEighths(scenes));
    return {
      text: plural(scenes.length, 'scene') + ' · '
        + pages + (pages === '1' ? ' page' : ' pages')
        + ' · ' + (noLoc ? noLoc + ' with no location' : 'every scene has a location')
    };
  },

  schedule() {
    const scenes = listScenes();
    if (!scenes.length) return EMPTY_FILM;
    const d = calendarDays(scenes).length;
    const people = listContacts().length;
    return {
      text: (d ? plural(d, 'shoot day') : 'No shoot days yet') + ' · ' + plural(people, 'person', 'people')
    };
  },

  shoot() {
    const scenes = listScenes();
    if (!scenes.length) return EMPTY_FILM;
    const all = shootDays(scenes);
    if (!all.length) {
      return { text: plural(scenes.length, 'scene') + ' · none on a shoot day yet', empty: true, cta: 'stripboard' };
    }
    const day = pickDay(scenes);
    const at = all.findIndex((x) => x.day === day);
    const shot = scenes.filter((s) => s.shotState === 'shot').length;
    return {
      text: 'Day ' + (at + 1) + ' of ' + all.length + ' · ' + plural(shot, 'scene') + ' shot'
    };
  },

  draft() {
    const els = loadScript().elements || [];
    if (!els.length) return { text: 'No pages in Write yet', empty: true, cta: 'screenplay' };
    const scenes = els.filter((e) => e.type === 'scene').length;
    return {
      text: formatPages(pageCount(els)) + ' pages · ' + plural(scenes, 'scene') + ' in the script'
    };
  }
};

/** Fill every readout slot on the page. Reads only. */
export function refreshReadouts(root = document) {
  root.querySelectorAll('[data-st-readout]').forEach((slot) => {
    const fn = READOUTS[slot.getAttribute('data-st-readout')];
    if (!fn) return;
    let r;
    try { r = fn(); } catch (e) { r = null; }
    if (!r) { slot.replaceChildren(); return; }
    slot.classList.toggle('is-empty', !!r.empty);
    const kids = [h('span.st-readout-text', { text: r.text })];
    const cta = r.empty && r.cta ? resolveTool(r.cta) : null;
    if (cta) kids.push(h('a.btn.st-tool', { href: cta.href, text: 'Open ' + cta.label + ' →' }));
    slot.replaceChildren(...kids);
  });
}

/* Coming back from the Breakdown in another tab is the moment the
   numbers changed, so that is when they are read again. Bound once. */
let watching = false;
export function watchReadouts() {
  refreshReadouts();
  if (watching || typeof document === 'undefined') return;
  watching = true;
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') refreshReadouts();
  });
}

export default {
  stageInfo, stageRow, stageChips, partsOf, partLabel, partHeading, idsInPart,
  resolveTool, refreshReadouts, watchReadouts, roman, numberWord, capitalise
};
