/* ============================================================
   THE FILMMAKER'S LIBRARY — page entry
   ------------------------------------------------------------
   The legacy page (legacy/arunak-filmmaker-library.html) was
   1,559 lines of hand-written markup: 22 film cards, 10 director
   cards, 50 rule cards, 6 rate tables and 24 watch-list blocks,
   all typed out by hand, plus a cover whose table of contents
   quoted counts ("22 films", "50 rules", "72-film watch list")
   that nothing kept honest. Editing the data meant editing the
   prose in five places and hoping.

   Everything below renders from src/data/*.json instead, and
   every count on the page is `array.length`. The cover blurb,
   the TOC lines, the section-head counters and the deck prose
   cannot disagree with the cards, because they are the same
   number.

   THE REFERENCE SHELF (6 Oct 2026, owner's ask). Case Studies,
   Dissection and the Craft Glossary used to be Story-stage modules
   on pages of their own. They are tabs here now, beside the films and
   the rules they draw on: navigation.json hangs them off the Library's
   global entry (src/lib/navmodel.js), study.html and dissect.html are
   redirect stubs, and the two renderers moved — ONE copy each — to
   src/ui/case-studies.js and src/ui/dissection.js. Every storage key
   they touch (fms_studio_demo_v1, fms_workbench_v1, fms_dissect_v1)
   is owned by its lib module and did not move.

   TABS. tabs.js turns the `section[id]` children of <main> into tabs,
   so each head and its body are ONE section with the id on it. They
   used to be two siblings — a `section.section-head#films` and an
   anonymous `section.section-body` after it — which tabbed the
   headings and left all eight bodies on screen at once. The cover and
   the closing page carry no id on purpose: they stay outside the tabs.

   ⚠️  LOAD ORDER — store.js FIRST.
   It patches Storage.prototype so `fms_library_calc_v1` is
   scoped to the current project. The calculator's load/save must
   run after that patch is installed. See the banner in
   src/lib/store.js.
   ============================================================ */

import '../lib/store.js';

import '../styles/base.css';
import '../styles/chrome.css';
import '../styles/editorial.css';
import '../styles/widgets.css';
import '../styles/modules.css';
import '../styles/rates.css';
import '../styles/print.css';
import '../styles/library-shelf.css';

import StudioUI from '../ui/chrome.js';
import { mountShell } from '../ui/shell.js';
import { h, delegate } from '../lib/dom.js';
import { shelves } from '../lib/navmodel.js';
import PlanGate from '../lib/plan-gate.js';
import { mountCaseStudies } from '../ui/case-studies.js';
import { mountDissection } from '../ui/dissection.js';
import { listStudies } from '../lib/studies.js';
import { listShipped } from '../lib/dissect.js';

import films from '../data/films.json';
import directors from '../data/directors.json';
import rules from '../data/rules.json';
import watchlist from '../data/watchlist.json';
import featureSteps from '../data/steps.feature.json';
import productionSteps from '../data/steps.production.json';
import rates from '../data/rates.chennai.2024.json';
/* The 2026 verification layer. It is a SEPARATE file on purpose:
   rates.chennai.2024.json is regenerated byte-for-byte from legacy/
   by `npm run extract`, so provenance written into it is deleted by
   the next extraction with no warning. Same arrangement as
   steps.production.json beside the extracted steps.feature.json.
   The base file's name is still true — it is the 2024-25 card. What
   is 2026 is in the overlay and is labelled as such, per figure. */
import rateChecks from '../data/rates.chennai.checks.json';
import glossary from '../data/glossary.json';


/* The theme toggle's tooltip, derived from the list it describes.
   This one said "Cycle theme (paper → sepia → ink)" — a fifth
   hand-written copy of StudioUI.themeOrder(), and the one that
   survived the first sweep because it was worded differently from
   the other four. A list spelled out in five places is wrong in five
   places the moment the list changes. */
function themeTitle() {
  const order = (StudioUI.themeOrder && StudioUI.themeOrder()) || [];
  return order.length ? `Cycle theme (${order.join(' → ')})` : 'Cycle theme';
}
/* ============================================================
   DERIVED COUNTS — the single source for every number the page
   says out loud.
   ============================================================ */
const N_FILMS      = films.length;
const N_DIRECTORS  = directors.length;
const N_RULES      = rules.length;
const N_STEPS      = watchlist.length;
/* The watch list covers the writing half only (steps 01-24); the Feature
   Blueprint itself runs on through production and post. Say both numbers,
   or "the 24 blueprint steps" contradicts the blueprint's own count. */
const N_BLUEPRINT  = featureSteps.vol1.length + featureSteps.vol2.length +
                     productionSteps.production.length + productionSteps.post.length;
const N_WATCHFILMS = watchlist.reduce((n, s) => n + s.films.length, 0);
const N_TABLES     = rates.sections.length;
const N_STUDIES    = listStudies().length;
const N_DISSECTED  = listShipped().length;
const N_TERMS      = (glossary.terms || []).length;
const N_GLOSS_FILMS = Object.keys(glossary.films || {}).length;
/* Films-per-step is a fact about the data, not a constant: if a
   step ever carried four, the deck would say four. */
const FILMS_PER_STEP = Math.round(N_WATCHFILMS / Math.max(1, N_STEPS));

const ROMAN = ['0', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'];

const UNITS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven',
  'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen',
  'sixteen', 'seventeen', 'eighteen', 'nineteen'];
const TENS = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy',
  'eighty', 'ninety'];

/** "Fifty rules of thumb" has to still read like English when the
 *  JSON gains a rule. Words below 100, digits above. */
function numWord(n) {
  if (!Number.isInteger(n) || n < 0 || n > 99) return String(n);
  if (n < 20) return UNITS[n];
  const t = TENS[Math.floor(n / 10)];
  const u = n % 10;
  return u ? `${t}-${UNITS[u]}` : t;
}
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/* ---- rate provenance --------------------------------------
   The rate card is a snapshot, and the snapshot has a date. A
   reader pricing a shoot against it is entitled to know how old
   it is, computed now rather than asserted once and left to rot. */
function rateAge() {
  const firstYear = parseInt(String(rates.asOf).match(/\d{4}/)?.[0] ?? '', 10);
  const now = new Date().getFullYear();
  if (!firstYear || now <= firstYear) return null;
  return now - firstYear;
}
function provenanceLine() {
  const age = rateAge();
  const asOf = rates.asOf;
  if (!age) return `Rate card as of ${asOf}.`;
  const span = age === 1 ? 'about a year old' : `about ${numWord(age)} years old`;
  return `Rate card as of ${asOf} — ${span}. Most of these figures have not been ` +
         `updated since; treat them as historical and re-quote before you budget.`;
}

/* ---- the 2026 check layer ---------------------------------
   Keyed by section id then by the row's `item` string, because a
   rate row has no id of its own. That makes the join fragile in one
   specific way — rename an item in the base file and its check
   silently stops matching — so nothing is dropped on a miss:
   unmatched checks are collected and rendered under their section
   as their own note. A check that quietly disappears is the same
   class of bug as a CSS variable that is never defined. */
const CHECKS_BY_SECTION = (() => {
  const map = new Map();
  for (const row of (rateChecks.rows || [])) {
    if (!map.has(row.section)) map.set(row.section, []);
    map.get(row.section).push(row);
  }
  return map;
})();

const CONFIDENCE_LABEL = {
  checked: 'CHECKED',
  corroborating: 'CONTEXT',
  stale: 'NOT UPDATED'
};

function checksFor(sectionId, item) {
  return (CHECKS_BY_SECTION.get(sectionId) || []).filter((c) => c.item === item);
}

function sourceOf(id) {
  return (rateChecks.sources || {})[id] || null;
}

/** One line of evidence under a rate, or the reason there is none. */
function renderCheck(c) {
  const src = sourceOf(c.source);
  const line = h('div.rate-check', { 'data-confidence': c.confidence }, [
    h('span.rate-check-tag', { text: CONFIDENCE_LABEL[c.confidence] || 'NOTE' })
  ]);
  if (c.raw) line.append(h('span.rate-check-val', { text: c.raw }));
  if (src) {
    line.append(h('span.rate-check-src', {}, [
      h('a', {
        href: src.url, target: '_blank', rel: 'noopener noreferrer',
        text: src.name
      }),
      `, checked ${c.checked}`
    ]));
  } else if (c.checked) {
    line.append(h('span.rate-check-src', { text: `Looked for on ${c.checked}; nothing published found.` }));
  }
  if (c.caveat) line.append(h('span.rate-check-caveat', { text: c.caveat }));
  return line;
}

/* ============================================================
   SECTIONS — one list drives the toolbar nav, the cover TOC and
   the five section heads. Three copies became one.
   ============================================================ */
const SECTIONS = [
  {
    id: 'films',
    nav: 'FILMS',
    tab: 'Films',
    title: 'The Tamil Cinema <em>Craft Library.</em>',
    tocTitle: 'Tamil Cinema Craft Library',
    tocDesc: `${N_FILMS} films, what to learn from each`,
    count: `${N_FILMS} FILMS`,
    deck: `${cap(numWord(N_FILMS))} films, mostly Tamil with a few Malayalam ` +
          `neighbours. For each one, the single craft lesson worth taking. ` +
          `Not reviews — extractable techniques you can apply to your own work.`,
    body: renderFilms
  },
  {
    id: 'directors',
    nav: 'DIRECTORS',
    tab: 'Directors',
    title: 'Director <em>Archetypes.</em>',
    tocTitle: 'Director Archetypes',
    tocDesc: `${N_DIRECTORS} voices to study`,
    count: `${N_DIRECTORS} ARCHETYPES`,
    deck: `${cap(numWord(N_DIRECTORS))} directors whose grammar is distinct ` +
          `enough to study as schools of filmmaking. For each: the signature ` +
          `traits, the film to start with, and a Tanglish gloss on what makes ` +
          `them unique.`,
    body: renderDirectors
  },
  {
    id: 'rules',
    nav: 'RULES',
    tab: 'Rules',
    title: `${cap(numWord(N_RULES))} <em>Rules of Thumb.</em>`,
    tocTitle: `${N_RULES} Rules of Thumb`,
    tocDesc: 'Craft maxims, attributed',
    count: `${N_RULES} RULES`,
    deck: `Craft maxims, attributed where the source is known. Treat them as ` +
          `starting points, not laws — every great film breaks at least one.`,
    body: renderRules
  },
  {
    id: 'equipment',
    nav: 'EQUIPMENT',
    tab: 'Equipment',
    /* The estimator moved to budget.html; this section kept only the
       rate tables, and its title still advertised the calculator and
       told the reader to "use the calculator at the bottom". It names
       what is here now, and the deck routes to the Budget page. */
    title: 'Equipment &amp; <em>Rates.</em>',
    tocTitle: 'Equipment & Rates',
    tocDesc: `Chennai ${rates.asOf} indicative ranges, some re-checked ${rateChecks.lastChecked}`,
    count: `${N_TABLES} RATE TABLES · ${rates.asOf}`,
    deck: `Indicative daily rental ranges, Chennai market, ${rates.asOf}, in ` +
          `${numWord(N_TABLES)} tables. The Budget page reads them to ` +
          `estimate kit cost for your shoot. Rates fluctuate; verify with ` +
          `vendors before locking your budget.`,
    body: renderEquipment
  },
  {
    id: 'watch',
    nav: 'WATCH LIST',
    tab: 'Watch list',
    title: 'Watch List <em>per Step.</em>',
    tocTitle: 'Watch List per Step',
    tocDesc: `${FILMS_PER_STEP} films for each of the first ${N_STEPS} of ${N_BLUEPRINT} blueprint steps`,
    count: `${N_WATCHFILMS} FILMS · ${N_STEPS} STEPS`,
    deck: `For every one of the first ${N_STEPS} blueprint steps (story and writing; the ` +
          `Feature Blueprint runs to ${N_BLUEPRINT}), ${numWord(FILMS_PER_STEP)} ` +
          `films to study for that exact craft concept. ${N_WATCHFILMS} films total. ` +
          `Watch them with the step's question in mind — the films will teach you ` +
          `more than the blueprint can.`,
    body: renderWatchlist
  },
  /* The reference shelf. The tab label is the navigation.json module's
     label (shelfLabel), so the rail, the palette, the hub's map and
     this strip cannot name one tool three ways. */
  {
    id: 'case-studies',
    nav: 'CASE STUDIES',
    title: 'Case <em>Studies.</em>',
    tocTitle: 'Case Studies',
    tocDesc: `${N_STUDIES} films, read beat by beat`,
    count: `${N_STUDIES} FILMS`,
    deck: `Pick one of ${numWord(N_STUDIES)} films and every card below speaks in its ` +
          `terms: the concept, the logline, the characters, the beats, the scene ` +
          `craft. Each card is the same three steps — what the thing is, how this ` +
          `film did it, how to write yours.`,
    body: renderCaseStudiesHost
  },
  {
    id: 'dissection',
    nav: 'DISSECTION',
    title: 'Film <em>Dissection.</em>',
    tocTitle: 'Film Dissection',
    tocDesc: 'A finished film taken apart, then yours',
    count: `${N_DISSECTED} WORKED ${N_DISSECTED === 1 ? 'EXAMPLE' : 'EXAMPLES'}`,
    deck: 'The blueprints build a script forwards. This runs the other way: ' +
          'start with a film that works, and name the job every sequence is doing. ' +
          'Read the worked example, then fill the same fields in about yours.',
    body: renderDissectionHost
  },
  {
    id: 'glossary',
    nav: 'GLOSSARY',
    title: 'Craft <em>Glossary.</em>',
    tocTitle: 'Craft Glossary',
    tocDesc: `${N_TERMS} terms, each in ${numWord(N_GLOSS_FILMS)} films`,
    count: `${N_TERMS} TERMS · ${N_GLOSS_FILMS} FILMS`,
    deck: `${cap(numWord(N_TERMS))} craft terms the studio uses, each defined once ` +
          `and then shown at work in ${numWord(N_GLOSS_FILMS)} Tamil films. The same ` +
          `definitions open as popovers wherever a term appears in the blueprints.`,
    body: renderCraftGlossary
  }
];

/** A shelf module's label from navigation.json, for the tab strip. */
function shelfLabel(id) {
  for (const sh of shelves()) for (const m of sh.modules) {
    if ((m.href || '').split('#')[1] === id) return m.label;
  }
  return '';
}

/* ============================================================
   CHROME
   ============================================================ */
function renderToolbar() {
  /* A div, not a <header role="banner">, and no wordmark.

     Both for the same reason: this strip is no longer the top of the
     page. shell.js adopts it into .sh-bar as that band's right-hand
     zone, and .sh-bar is role="navigation" — a banner landmark nested
     inside a navigation one is a landmark tree that lies about the
     page. The band above IS the banner. "Arunak" went with it: the
     breadcrumb two inches to the left says "Studio › Library", and the
     cover byline and the colophon both still carry the name. */
  return h('div.toolbar', {}, [
    h('a#studioProjLink.studio-proj-link', {
      href: 'index.html',
      title: 'Back to Studio · current project'
    }, [
      h('span.spl-arrow', { text: '←', 'aria-hidden': 'true' }),
      h('span#studioProjLabel.spl-label', { text: 'STUDIO' })
    ]),
    // HUB / FEATURE / SHORTS removed: the shell's rail and phase bar
    // carry them now, and three more links in a strip was the problem.
    h('nav.nav-jump', { 'aria-label': 'Library sections' },
      SECTIONS.map((s) => h('a.nav-link', { href: `#${s.id}`, text: s.nav }))),
    // No inline onclick anywhere on this page — see wireActions().
    h('button#darkBtn.btn.icon-btn', {
      type: 'button',
      'data-action': 'theme',
      title: themeTitle(),
      'aria-label': 'Cycle theme',
      text: '◐'
    }),
    h('button.btn', { type: 'button', 'data-action': 'print', text: 'PRINT' })
  ]);
}

/* ============================================================
   COVER
   ============================================================ */
function renderCover() {
  const blurb =
    `A curated reference: ${N_FILMS} Tamil & Indian films analyzed for craft, ` +
    `${N_DIRECTORS} director archetypes, ${N_RULES} craft rules, equipment cost ` +
    `ranges (Chennai ${rates.asOf}), and a ${N_WATCHFILMS}-film watch list mapped ` +
    `to every step of the blueprint.`;

  return h('section.cover', {}, [
    h('div', {}, [
      h('div.cover-mark', { text: 'A reference companion to The Filmmaker\'s Blueprint' }),
      h('h1.cover-title', {}, [
        'The ', h('span.light', { text: 'Filmmaker\'s' }), h('br'), 'Library.'
      ]),
      h('p.cover-sub', { text: blurb }),
      h('nav.cover-toc', { 'aria-label': 'Contents' },
        SECTIONS.map((s, i) => h('a.toc-item', { href: `#${s.id}` }, [
          h('span.num', { text: `SECTION ${ROMAN[i + 1] || i + 1}` }),
          h('span.title', { text: s.tocTitle }),
          h('span.desc', { text: s.tocDesc })
        ])))
    ])
  ]);
}

/* One section per tab: the id, the head and the body together. */
function renderSection(section, i) {
  const sec = h('section.lib-sec', {
    id: section.id,
    'data-tab-label': shelfLabel(section.id) || section.tab || section.nav
  });
  sec.append(renderSectionHead(section, i), section.body());
  return sec;
}

function renderSectionHead(section, i) {
  return h('div.section-head', {}, [
    h('div.left', {}, [
      h('div.label', { text: `SECTION ${ROMAN[i + 1] || i + 1}` }),
      h('h2', { html: section.title }),
      h('p.deck', { text: section.deck })
    ]),
    // The count is read off the same array the cards come from,
    // so the header can never claim a number the body doesn't have.
    h('div.right', { text: section.count })
  ]);
}

/* ============================================================
   SECTION I — FILMS
   ============================================================ */
function renderFilms() {
  return h('section.section-body', {}, [
    h('div.films-grid', {}, films.map((f) => h('article.film-card', {}, [
      h('div.meta', { text: f.meta }),
      h('h3', { text: f.title }),
      h('div.director', { text: f.director }),
      h('div.tags', {}, (f.tags || []).map((t) => h('span.tag', { text: t }))),
      h('p.lesson', { html: f.lesson }, [
        f.tanglish ? h('span.tn', { html: f.tanglish }) : null
      ])
    ])))
  ]);
}

/* ============================================================
   SECTION II — DIRECTORS
   ============================================================ */
function renderDirectors() {
  return h('section.section-body', {}, directors.map((d) => {
    const traits = h('dl.traits');
    for (const t of d.traits || []) {
      traits.append(h('dt', { text: t.term }), h('dd', { text: t.value }));
    }
    return h('article.director-card', {}, [
      h('div.name-row', {}, [
        h('h3', { text: d.name }),
        h('span.era', { text: d.era })
      ]),
      traits,
      d.study ? h('div.study', {}, [
        h('div.lab', { text: d.study.label }),
        h('p', { html: d.study.body })
      ]) : null,
      d.tanglish ? h('span.tn', { html: d.tanglish }) : null
    ]);
  }));
}

/* ============================================================
   SECTION III — RULES
   ------------------------------------------------------------
   The numbers are a CSS counter on .rules-grid, so they follow
   the rendered order rather than a hand-typed `n`. The data's
   own `n` rides along as data-n for anyone diffing.
   ============================================================ */
function renderRules() {
  return h('section.section-body', {}, [
    h('div.rules-grid', {}, rules.map((r) => h('div.rule-card', { 'data-n': r.n }, [
      h('p.rule-text', { text: r.text }),
      h('p.attrib', { text: r.attribution })
    ])))
  ]);
}

/* ============================================================
   SECTION IV — EQUIPMENT & COST ESTIMATOR
   ============================================================ */
function renderEquipment() {
  const body = h('section.section-body');

  body.append(h('div.disclaimer', {}, [
    h('div.label', { text: rates.noteLabel }),
    h('p', { html: rates.note }),
    h('p.hint', { text: provenanceLine() }),
    h('p.hint', {
      text: `Re-checked on ${rateChecks.lastChecked}. ${rateChecks.method}`
    })
  ]));

  for (const sec of rates.sections) {
    const block = h('div.equip-block', { id: `rates-${sec.id}` }, [
      h('h3', { text: sec.heading })
    ]);
    if (sec.note) block.append(h('p.hint', { text: sec.note }));
    // Provenance sits with each table, not only in the disclaimer
    // three screens up — that is where the eye actually is. It says
    // what the 2026 pass found for THIS section, which for four of
    // the six is "nothing published", stated rather than implied.
    const secNote = (rateChecks.sectionNotes || {})[sec.id];
    /* "Not updated since" was printed under every table, including the
       camera bodies, most of which carry a CHECKED row right below it.
       Say so only where nothing in the section was re-checked. */
    const anyChecked = (CHECKS_BY_SECTION.get(sec.id) || []).some((c) => c.confidence === 'checked');
    block.append(h('p.hint', {
      text: anyChecked
        ? `Rates as of ${rates.asOf}; rows marked CHECKED were re-checked on ${rateChecks.lastChecked}.`
        : `Rates as of ${rates.asOf}. Not updated since.`
    }));
    if (secNote) {
      const srcNote = sourceOf(secNote.source);
      block.append(h('p.hint.rate-section-check', { 'data-confidence': secNote.confidence }, [
        h('span.rate-check-tag', { text: CONFIDENCE_LABEL[secNote.confidence] || 'NOTE' }),
        ' ',
        secNote.text,
        srcNote ? ' ' : null,
        srcNote ? h('a', {
          href: srcNote.url, target: '_blank', rel: 'noopener noreferrer',
          text: srcNote.name
        }) : null
      ]));
    }

    const matched = new Set();
    const table = h('table.equip-table', {}, [
      h('caption.visually-hidden', {
        text: `${sec.heading} — indicative Chennai rates, ${rates.asOf}`
      }),
      h('thead', {}, [
        h('tr', {}, (sec.columns || []).map((c) => h('th', { scope: 'col', text: c })))
      ]),
      h('tbody', {}, (sec.rows || []).flatMap((r) => {
        const found = checksFor(sec.id, r.item);
        found.forEach((c) => matched.add(c));
        const rate = h('td.rate', {}, [
          // `raw` is the rate exactly as published in 2024-25.
          // Nothing here is recomputed, re-inflated or invented.
          h('span.rate-base', { text: r.raw })
        ]);
        found.forEach((c) => rate.append(renderCheck(c)));
        return [h('tr', {}, [
          h('td.item', { text: r.item }),
          rate,
          h('td.note', { text: r.note || '' })
        ])];
      }))
    ]);
    // Wide table, narrow phone: the table scrolls, the page doesn't.
    block.append(h('div.table-wrap', {}, [table]));

    // Anything in the overlay that matched no row is shown here
    // rather than dropped. The join is by item name and item names
    // can change; a silent miss would take the evidence with it.
    const orphans = (CHECKS_BY_SECTION.get(sec.id) || []).filter((c) => !matched.has(c));
    if (orphans.length) {
      block.append(h('div.rate-orphans', {}, [
        h('p.hint', {
          text: 'Checked, but no row in the table above carries this name any more:'
        }),
        ...orphans.map((c) => h('div.rate-check', {}, [
          h('span.rate-check-tag', { text: c.item }), renderCheck(c)
        ]))
      ]));
    }
    body.append(block);
  }

  if ((rateChecks.notFound || []).length) {
    body.append(h('div.rate-notfound', {}, [
      h('h3', { text: 'What could not be found' }),
      h('p.hint', {
        text: `Looked for on ${rateChecks.lastChecked} and not published anywhere `
            + 'this search could reach. Listed because an absence is a finding: '
            + 'it tells you which numbers you will have to get on the phone for.'
      }),
      h('ul', {}, rateChecks.notFound.map((t) => h('li', { text: t })))
    ]));
  }

  /* The estimator moved to budget.html. It used to render here, at
     the foot of the rate tables, while navigation.json listed Budget
     under PLAN pointing at `library.html#calculator` — an anchor that
     never existed. Rendering it in both places would mean two DOM
     trees writing to one storage key, so this is a route, not a copy. */
  body.append(h('div.calc-block.calc-moved', {}, [
    h('h3', { text: 'Working out what it costs' }),
    h('p.hint', {
      text: 'The line-item estimator reads these rates and your shoot days '
          + 'from the stripboard. It has its own page now.'
    }),
    h('a.btn.primary', { href: 'budget.html', text: 'OPEN THE BUDGET →' })
  ]));
  return body;
}

/* ============================================================
   SECTION V — WATCH LIST
   ============================================================ */
function renderWatchlist() {
  return h('section.section-body', {}, watchlist.map((step) => h('div.watch-step', {
    'data-vol': step.vol
  }, [
    // Was a <div class="step-tag"> inside an <a> carrying four
    // inline styles. One element, no inline style, still a link.
    h('a.step-tag', {
      href: `feature.html#${step.step}`,
      title: 'Jump to this step in the blueprint',
      text: `${step.label} ↗`
    }),
    h('h4', { text: step.heading }),
    h('div.watch-films', {}, (step.films || []).map((f) => h('div.watch-film', {}, [
      h('span.title', { text: `${f.title} (${f.year})` }),
      h('span.why', { text: f.why })
    ])))
  ])));
}

/* ============================================================
   SECTIONS VI & VII — CASE STUDIES, DISSECTION
   ------------------------------------------------------------
   Hosts only. The renderers live in src/ui/ and draw into these
   after the page is in the document (mountShelf below). A div, not
   `section.section-body`: the glossary tagger walks every
   section.section-body, and these two never had popovers on their
   own pages.
   ============================================================ */
function renderCaseStudiesHost() {
  return h('div.section-body.lib-embed', {}, [h('div#caseStudiesHost.lib-host')]);
}
function renderDissectionHost() {
  return h('div.section-body.lib-embed', {}, [h('div#dissectionHost.lib-host')]);
}
function mountShelf() {
  const cs = document.getElementById('caseStudiesHost');
  if (cs) mountCaseStudies(cs);
  const dx = document.getElementById('dissectionHost');
  if (dx) mountDissection(dx);
}

/* ============================================================
   SECTION VIII — CRAFT GLOSSARY
   ------------------------------------------------------------
   src/data/glossary.json, the file the popovers already read, shown
   whole: every term with every film's example. The case studies show
   one film's example per term; this is the reference shape, all four
   at once. The feature blueprint keeps its own department glossary
   (camera, coverage, production, budget, sound) at
   feature.html#glossary and this links to it rather than copying it.
   ============================================================ */
function renderCraftGlossary() {
  const films = glossary.films || {};
  const body = h('div.section-body.lib-gloss');

  body.append(h('div.st-gloss-filter', {}, [
    h('label.st-gloss-label', { for: 'libGlossFilter', text: 'Filter terms' }),
    h('input#libGlossFilter.st-gloss-input', {
      type: 'search', autocomplete: 'off', spellcheck: 'false',
      placeholder: 'subtext, setup, payoff…',
      'data-action': 'lib-gloss-filter', 'aria-controls': 'libGlossList'
    }),
    h('span#libGlossCount.st-gloss-count', {
      role: 'status', 'aria-live': 'polite', text: `${N_TERMS} terms`
    })
  ]));

  const list = h('div#libGlossList.gloss-list.st-gloss.lib-gloss-list');
  for (const t of (glossary.terms || [])) {
    const dt = h('dt', { text: t.term });
    if ((t.aliases || []).length) dt.append(h('span.st-alias', { text: ' · ' + t.aliases.join(', ') }));
    const item = h('article.gloss-item', {}, [h('dl', {}, [dt, h('dd', { text: t.def || '' })])]);
    if (t.tanglish) item.append(h('span.tn', { text: t.tanglish }));
    const ex = (t.examples || []).filter((e) => e && e.note);
    if (ex.length) {
      item.append(h('ul.lib-gloss-ex', {}, ex.map((e) => h('li', {}, [
        h('span.lib-gloss-film', { text: films[e.film] || e.film }),
        ' ' + e.note
      ]))));
    }
    item.setAttribute('data-search', [
      t.term, (t.aliases || []).join(' '), t.def, t.tanglish, ...ex.map((e) => e.note)
    ].filter(Boolean).join(' ').toLowerCase());
    list.append(item);
  }
  body.append(list);
  body.append(h('p#libGlossNone.st-gloss-none', {
    hidden: true,
    text: 'No term matches that. Try a shorter word — the definitions are searched too.'
  }));
  body.append(h('p.hint.lib-gloss-more', {}, [
    'Camera, coverage, production, budget and sound terms are in the ',
    h('a', { href: 'feature.html#glossary', text: 'feature blueprint’s glossary' }),
    '.'
  ]));
  return body;
}

function filterGlossary(input) {
  const q = String(input.value || '').trim().toLowerCase();
  const items = document.querySelectorAll('#libGlossList .gloss-item');
  let shown = 0;
  items.forEach((el) => {
    const hit = !q || (el.getAttribute('data-search') || '').includes(q);
    el.hidden = !hit;
    if (hit) shown++;
  });
  const count = document.getElementById('libGlossCount');
  if (count) count.textContent = q ? `${shown} of ${items.length} terms` : `${items.length} terms`;
  const none = document.getElementById('libGlossNone');
  if (none) none.hidden = shown !== 0;
}

/* ============================================================
   FINAL PAGE
   ============================================================ */
function renderFinal() {
  return h('section.final-page', {}, [
    h('p.quote', {}, [
      '"Watch films like a director, not an audience.', h('br'),
      'Then write films like an audience, not a director."'
    ]),
    h('div.signature', {}, ['THE FILMMAKER\'S LIBRARY'])
  ]);
}

/* ============================================================
   ACTIONS — one delegated listener, zero inline handlers.
   ============================================================ */
function toggleDark() {
  // Delegate to the shared 3-state theme in src/ui/chrome.js — local
  // toggling desynced the page class from StudioUI's stored theme.
  StudioUI.cycleTheme();
}

/* The calculator's actions went with it to src/ui/budget.js, which
   owns its own delegated listener now. What is left here is the
   page's own chrome. */
const ACTIONS = {
  theme: toggleDark,
  print: () => window.print()
};

function wireActions(root) {
  delegate(root, 'click', '[data-action]', (e, el) => {
    const fn = ACTIONS[el.dataset.action];
    if (!fn) return;
    e.preventDefault();
    /* Pass the element through. Every handler here used to take no
       arguments, so this changes nothing for them — but a handler that
       needs to read a data- attribute off the button had no way to,
       and failed silently when it tried. */
    fn(el, e);
  });

  // The glossary filter: DOM-only, so typing never re-renders and
  // never writes.
  delegate(root, 'input', '[data-action="lib-gloss-filter"]', (e, el) => filterGlossary(el));
}

/* ============================================================
   THEME
   ============================================================
   There used to be an adoptLegacyDarkPref() here, carrying the old
   Library page's dark toggle into the ink theme. It read an undefined
   PREF_KEY, so it never ran — and it never needed to: ink is the
   default, and chrome.js's loadTheme() already hands ink to anyone
   with no stored theme, which is exactly who it was for. */
function syncThemeButton() {
  const theme = document.body.classList.contains('dark') ? 'ink' : 'paper';
  // applyTheme also updates #darkBtn's glyph, which did not exist
  // when StudioUI ran its own boot.
  StudioUI.applyTheme(theme);
}

/* ============================================================
   BOOT
   ============================================================ */
function render() {
  const app = document.getElementById('app');
  if (!app) return;

  const toolbar = renderToolbar();

  // The toolbar is site chrome, not document content: it sits before
  // <main> so the skip link actually skips it — and mountShell() then
  // moves it into .sh-bar, which is also before <main>, so that stays
  // true after the adoption.
  const main = h('main#main', { role: 'main' });
  main.append(renderCover());
  SECTIONS.forEach((s, i) => main.append(renderSection(s, i)));
  main.append(renderFinal());

  app.replaceChildren(toolbar, main);

  wireActions(app);
  mountShelf();
  syncThemeButton();

  // StudioUI boots before this module renders, so the bits of it
  // that look for page furniture get a second, explicit call.
  try {
    mountShell();
    StudioUI.attachSignInPill(toolbar);
    StudioUI.upgradeThemeButton(toolbar);
    StudioUI.autoAriaLabels();
    // The craft rules and film notes are exactly where a term needs
    // explaining; .section-body is in the tagger's scope.
    StudioUI.wireGlossaryPopovers();
  } catch (e) { /* cloud/chrome extras are optional */ }
  // A shelf tab the plan does not include shows its lock card; the
  // rest of the Library stays open. See plan-gate.js, "the tab lock".
  try { PlanGate.lockTabs(); } catch (e) { /* not gated */ }
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', render);
} else {
  render();
}
