#!/usr/bin/env node
/* npm run test:brand — the product name and the seller's identity live in
   src/data/brand.json and nowhere else. Scans the shipped tree for strays. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const brand = JSON.parse(fs.readFileSync(path.join(ROOT, 'src/data/brand.json'), 'utf8'));
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const spaced = String(brand.name).replace(/([a-z])([A-Z])/g, '$1 $2');
const names = [...new Set([brand.name, spaced])];
const PATTERNS = [/arunak/i, /curated by/i, /arunaaron85/i, ...names.map((n) => new RegExp(esc(n), 'i')),
  // any spacing of the name: "Filmmaker Studio", "Film Maker Studio"
  new RegExp(brand.name.replace(/\s+/g, '').split('').map(esc).join('\\s?'), 'i')];

const SKIP_DIRS = new Set(['node_modules', 'legacy', 'docs', '.git', '.claude']);
// baseline.json is captured page words, not source: re-baselining after a
// rename refreshes it.
const SKIP_PATHS = ['src/data/brand.json', 'scripts/check-brand.mjs', 'scripts/extract/', 'scripts/baseline.json',
  // generated by scripts/make-icons.mjs, which reads brand.json
  'public/icons/'];
const TEXT = /\.(html|js|mjs|cjs|css|json|webmanifest|svg|txt|md|xml|toml|yml|yaml|map)$/i;

// Allowed lines: [file, regex the line must match]
const LINE_ALLOW = [
  ['src/lib/store.js', /arunak/i],
  ['src/lib/backup.js', /arunak/i],
  ['scripts/verify-migration.mjs', /arunak/i],
  // The backup FILE FORMAT id is deliberately fixed (backup.js FORMAT_ID),
  // so a rename never stops old or new backups being recognised.
  [null, /\b(_from|FORMAT_ID)\b/],
  [null, /"_comment"\s*:/]
];
// Old URLs (arunak-*.html stubs, the legacy sample file) are paths, not
// the brand, and the host is changed with its own checklist (LAUNCH §7).
const PATH_FORM = /arunak-[\w*.\[\]^/-]*/gi;
const HOST = new RegExp(esc(brand.host), 'gi');
// Comments are for the next developer, not the customer.
const COMMENT_LINE = /^\s*(\/\/|\/\*|\*|#|<!--)/;

const roots = ['src', 'public', 'extension', 'scripts'];
const files = fs.readdirSync(ROOT).filter((f) => f.endsWith('.html')).map((f) => f);
function walk(dir) {
  for (const e of fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true })) {
    const rel = dir + '/' + e.name;
    if (e.isDirectory()) { if (!SKIP_DIRS.has(e.name) && !e.name.startsWith('dist')) walk(rel); }
    else if (TEXT.test(e.name)) files.push(rel);
  }
}
roots.forEach((r) => fs.existsSync(path.join(ROOT, r)) && walk(r));

let hits = 0;
for (const rel of files) {
  if (SKIP_PATHS.some((p) => rel === p || rel.startsWith(p))) continue;
  const lines = fs.readFileSync(path.join(ROOT, rel), 'utf8').split('\n');
  const code = /\.(js|mjs|cjs|css)$/i.test(rel);
  let inBlock = false;
  lines.forEach((line, i) => {
    if (code) {
      const wasIn = inBlock;
      const opens = line.lastIndexOf('/*'), closes = line.lastIndexOf('*/');
      if (opens > closes) inBlock = true; else if (closes > opens) inBlock = false;
      if (wasIn && closes < 0) return;
      if (wasIn && closes >= 0 && !line.slice(closes + 2).trim()) return;
    }
    if (COMMENT_LINE.test(line)) return;
    const probe = line.replace(PATH_FORM, '').replace(HOST, '');
    if (!PATTERNS.some((re) => re.test(probe))) return;
    if (LINE_ALLOW.some(([f, re]) => (f === null || f === rel) && re.test(probe))) return;
    hits++;
    console.log(`${rel}:${i + 1}: ${line.trim().slice(0, 140)}`);
  });
}
if (hits) { console.error(`\ncheck-brand: ${hits} stray brand reference(s). Use src/data/brand.json / {{brand:*}} / src/lib/brand.js.`); process.exit(1); }
console.log('check-brand: clean');
