/* ============================================================
   TEST — script import: what the scene rows come out as, PINNED
   ------------------------------------------------------------
   src/lib/script-import.js in Node, no browser:

       node scripts/test-import.mjs   (or: npm run test:import)

   WHY THIS FILE EXISTS. docs/KNOWN-ISSUES.md §6: the importer had its
   own scene slicer (`sliceScenes`) beside the one every other module
   reads (`sliceScript` in src/lib/screenplay-analysis.js), and the two
   were not byte-identical on RAW element arrays — the shared one trims
   the heading and drops empty elements (an empty heading included),
   the importer's kept both. Folding them could only be allowed with a
   test that pins what an import PRODUCES first. This is that test.

   The fixtures are chosen for exactly the inputs where the two could
   have disagreed: blank lines, trailing whitespace, a preamble above
   the first heading, a heading followed at once by another (an empty
   scene), a heading paragraph with no text at all (.fdx), a heading
   with inner runs of spaces, and a numbered heading. The expected rows
   below were captured from the importer BEFORE the merge and are not
   regenerated by the test — change them only on purpose.

   The second half asserts the reason the merge is safe: every parser
   already emits trimmed, non-empty text, so the slicer never sees the
   inputs the two implementations differed on. Should a parser ever
   start emitting an empty or untrimmed element, that assertion is the
   one that fails, and it fails before any row does.
   ============================================================ */
import { mem } from './node-seams.mjs';
void mem;

const { DOMParser } = await import('linkedom');
globalThis.DOMParser = DOMParser;

const I = await import('../src/lib/script-import.js');
const A = await import('../src/lib/screenplay-analysis.js');

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) pass++; else { fail++; console.log('  ✗ ' + m); } };
const eq = (a, b, m) => ok(JSON.stringify(a) === JSON.stringify(b), `${m}\n      got  ${JSON.stringify(a)}\n      want ${JSON.stringify(b)}`);

/* A row, with the generated id and the per-row defaults left out, so
   the pin is about what the IMPORT decided and nothing else. */
const pin = (r) => [r.number, r.intExt, r.dayNight, r.location, r.eighths, r.synopsis];

/* ---- fixtures ----------------------------------------------------- */

const FOUNTAIN = [
  'Title: The Kettle   ',
  'Author: A. Writer',
  '',
  'FADE IN:',
  '',
  '   ',
  'INT. TEA STALL - DAY   ',
  '',
  'Steam off a kettle.   RAVI, 30s, counts coins.  ',
  '',
  'RAVI',
  '(quietly)',
  'Not today.',
  '',
  '',
  'EXT. HIGHWAY - NIGHT',
  'INT. RAVI HOUSE - CONTINUOUS',
  '',
  'He drops the coins.',
  '',
  '12  INT.  KITCHEN   -  MORNING',
  '',
  'A pan.  ',
  '',
  'CUT TO:',
  '',
  'EXT. YARD - LATER',
  '',
  '',
  ''
].join('\n');

/* The PDF route: positions are the types. Slugs at the margin, cues at
   col 20+, dialogue at col 10, a parenthetical at col 15, page numbers,
   (MORE) and (CONTINUED) lines, and a slug with trailing spaces. */
const TEXT = [
  '',
  '',
  'THE KETTLE',
  '',
  'FADE IN:',
  '',
  'INT. TEA STALL - DAY    ',
  '',
  'Steam off a kettle. RAVI, 30s, counts coins.',
  '',
  '                    RAVI',
  '               (quietly)',
  '          Not today. I said not',
  '          today.',
  '',
  '                                        2.',
  '',
  'EXT. HIGHWAY - NIGHT',
  'INT. RAVI HOUSE - CONTINUOUS',
  '',
  'He drops the coins.   ',
  '                    (MORE)',
  '',
  '(CONTINUED)',
  '',
  '12  INT.  KITCHEN   -  MORNING',
  '',
  'A pan.',
  '',
  '                                        CUT TO:',
  '',
  'EXT. YARD - LATER',
  '',
  ''
].join('\n');

const P = (type, text, attrs = '') => `<Paragraph Type="${type}"${attrs}><Text>${text}</Text></Paragraph>`;
const FDX = `<?xml version="1.0" encoding="UTF-8"?>
<FinalDraft DocumentType="Script" Template="No" Version="3">
<Content>
${P('Action', 'FADE IN:')}
${P('Scene Heading', '  INT. TEA STALL - DAY  ', ' Number="1"')}
${P('Action', 'Steam off a kettle. RAVI, 30s, counts coins.')}
${P('Character', 'RAVI')}
${P('Parenthetical', '(quietly)')}
${P('Dialogue', 'Not today.')}
${P('Action', '   ')}
${P('Scene Heading', '', ' Number="2"')}
${P('Scene Heading', 'EXT. HIGHWAY - NIGHT', ' Number="3"')}
${P('Scene Heading', 'INT. RAVI HOUSE - CONTINUOUS')}
${P('Action', 'He drops the coins.')}
${P('Scene Heading', '12  INT.  KITCHEN   -  MORNING', ' Number="12"')}
${P('Action', 'A pan.')}
${P('Transition', 'CUT TO:')}
${P('Scene Heading', 'EXT. YARD - LATER')}
</Content>
</FinalDraft>`;

const FIXTURES = [
  { name: 'fountain', raw: FOUNTAIN, file: 'kettle.fountain' },
  { name: 'text (PDF-shaped)', raw: TEXT, file: 'kettle.txt' },
  { name: 'fdx', raw: FDX, file: 'kettle.fdx' }
];

/* ---- 1. the pinned import --------------------------------------- */

/* Captured from the importer at commit a4d29ca, before sliceScenes()
   was folded into sliceScript(). Scene 2 (the highway) is a heading
   followed at once by the next heading: an EMPTY scene, kept, with the
   one-line minimum of one eighth. */
const EXPECTED = {
  /* Fountain: a heading on the line right under another heading, with
     no blank line between, is one BLOCK with it and reads as action —
     that is Fountain's own rule, so the highway scene swallows the
     RAVI HOUSE line as its synopsis and there are four scenes, not
     five. "YARD - LATER" keeps LATER in the place and guesses DAY,
     because LATER names no time of day. */
  'fountain': [
    ['1', 'INT', 'DAY', 'TEA STALL', 1, 'Steam off a kettle. RAVI, 30s, counts coins.'],
    ['2', 'EXT', 'NIGHT', 'HIGHWAY', 1, 'INT. RAVI HOUSE - CONTINUOUS'],
    ['12', 'INT', 'DAY', 'KITCHEN', 1, 'A pan.'],
    ['4', 'EXT', 'DAY', 'YARD - LATER', 1, '']
  ],
  /* The text route reads positions line by line, so the back-to-back
     heading IS a heading: an empty scene of one eighth. */
  'text (PDF-shaped)': [
    ['1', 'INT', 'DAY', 'TEA STALL', 1, 'Steam off a kettle. RAVI, 30s, counts coins.'],
    ['2', 'EXT', 'NIGHT', 'HIGHWAY', 1, ''],
    ['3', 'INT', 'CONTINUOUS', 'RAVI HOUSE', 1, 'He drops the coins.'],
    ['12', 'INT', 'DAY', 'KITCHEN', 1, 'A pan.'],
    ['5', 'EXT', 'DAY', 'YARD - LATER', 1, '']
  ],
  /* .fdx: the file's Number= attributes win (1, 3, 12); the heading
     paragraph with no text was never a heading, so its Number="2" is
     not reserved and the two unnumbered scenes take positions 4 and 5. */
  'fdx': [
    ['1', 'INT', 'DAY', 'TEA STALL', 1, 'Steam off a kettle. RAVI, 30s, counts coins.'],
    ['3', 'EXT', 'NIGHT', 'HIGHWAY', 1, ''],
    ['4', 'INT', 'CONTINUOUS', 'RAVI HOUSE', 1, 'He drops the coins.'],
    ['12', 'INT', 'DAY', 'KITCHEN', 1, 'A pan.'],
    ['5', 'EXT', 'DAY', 'YARD - LATER', 1, '']
  ]
};

const EXPECTED_COUNTS = {
  'fountain': { transition: 2, scene: 4, action: 4, character: 1, paren: 1, dialogue: 1 },
  'text (PDF-shaped)': { action: 4, transition: 2, scene: 5, character: 1, paren: 1, dialogue: 1 },
  'fdx': { action: 4, scene: 5, character: 1, paren: 1, dialogue: 1, transition: 1 }
};
const EXPECTED_NUMBERING = {
  'fountain': { fromFile: 0, fromHeading: 1, ordinal: 3, conflicted: 0, duplicated: 0 },
  'text (PDF-shaped)': { fromFile: 0, fromHeading: 1, ordinal: 4, conflicted: 0, duplicated: 0 },
  'fdx': { fromFile: 3, fromHeading: 0, ordinal: 2, conflicted: 0, duplicated: 0 }
};

const results = {};
for (const f of FIXTURES) {
  const r = I.parseScript(f.raw, f.file);
  results[f.name] = r;
  if (process.env.DUMP) {
    console.log('--', f.name);
    console.log(JSON.stringify(r.scenes.map(pin)));
    console.log(JSON.stringify(r.counts), JSON.stringify(r.numbering));
  }
  eq(r.scenes.map(pin), EXPECTED[f.name], `${f.name}: the scene rows are what the import produced before the merge`);
  eq(r.counts, EXPECTED_COUNTS[f.name], `${f.name}: the element counts`);
  eq(r.numbering, EXPECTED_NUMBERING[f.name], `${f.name}: where the numbers came from`);
  ok(r.scenes.length === r.elements.filter((e) => e.type === 'scene').length,
    `${f.name}: one row per heading element, the empty scene included`);
}

/* The text and .fdx routes agree on everything but the .fdx Number
   attributes (which only that format can carry), so the same script
   arriving two ways is the same film. Fountain is left out of this one
   on purpose: its blank-line rule reads the fixture differently, and
   that is pinned above. */
const strip = (rows) => rows.map((r) => pin(r).slice(1));
eq(strip(results['fdx'].scenes), strip(results['text (PDF-shaped)'].scenes), 'text and fdx agree on every field but the number');
eq(results['fdx'].numbering.fromFile, 3, '.fdx: three headings carried a Number= attribute (the empty one was never a heading)');
eq(results['fountain'].numbering.fromHeading, 1, 'fountain: one heading carried its number in the text');

/* ---- 2. why the merge is safe ------------------------------------- */

for (const f of FIXTURES) {
  const els = results[f.name].elements;
  ok(els.every((e) => String(e.text).trim() === e.text), `${f.name}: every element's text is trimmed by the parser`);
  ok(els.every((e) => e.text !== ''), `${f.name}: no parser emits an empty element`);
  ok(!els.some((e) => /\s{2,}/.test(e.text) && e.type !== 'scene') || f.name === 'fountain',
    `${f.name}: inner runs of spaces were folded`);
}

/* ---- 3. ONE slicer ------------------------------------------------- */

ok(I.sliceScenes === A.sliceScript, 'script-import re-exports sliceScript as sliceScenes — one implementation, not two');
const raw = [
  { type: 'action', text: 'FADE IN:' },
  { type: 'scene', text: '  INT. A - DAY  ' },
  { type: 'action', text: '' },
  { type: 'action', text: 'One.' },
  { type: 'scene', text: '   ' },
  { type: 'action', text: 'Two.' },
  { type: 'scene', text: 'EXT. B - NIGHT' }
];
const slices = I.sliceScenes(raw);
eq(slices.map((s) => s.heading), ['INT. A - DAY', 'EXT. B - NIGHT'],
  'on a RAW array the one slicer trims the heading and does not open a scene on a blank one — the way scene-sync.js headingsOf() counts headings');
eq(slices[0].elements.map((e) => e.text), ['One.', 'Two.'],
  'a blank heading does not cut the scene; the empty element is dropped');
eq(slices.map((s) => s.index), [0, 1], 'index is the heading position among the headings');

/* And through the importer the same raw array gives the same rows the
   editor's own sync would: two scenes, not three. */
const rows = I.scenesFrom(raw).rows.map(pin);
eq(rows.map((r) => r[3]), ['A', 'B'], 'scenesFrom() on a raw array: two scenes, the blank heading is not one');

console.log(`${fail ? '✗' : '✓'} script import: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
